# This is the "Ingredients List" for your custom Aurora KDE image.
name: aurora-t480-image
description: A custom Aurora image for my Lenovo T480 with hardware fixes.

# This is the most important line: it starts with the official Aurora KDE image.
base: ghcr.io/aurora-os/aurora-kde
from: latest

modules:
  - type: rpm-ostree
    repos:
      # Add the RPM Fusion repositories for multimedia codecs.
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

    install:
      # -- Lenovo T480 Specific Fixes --
      - tlp             # Advanced power management
      - tlp-rdw         # TLP's radio device wizard
      - throttled       # To prevent CPU thermal throttling
      - zcfan           # Advanced fan control daemon
      - python3-validity # For the fingerprint reader

      # -- Multimedia Codecs --
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-ugly
      - gstreamer1-vaapi
      - intel-media-driver # Video acceleration for Intel GPUs

      # -- Useful Utilities --
      - distrobox       # Run other Linux distributions in containers
